# This is a basic workflow to help you get started with Actions

name: GitHub CI

on: [pull_request]

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         persist-credentials: false
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run Spock test
        run:  ./gradlew test -Dgrails.env=test -Duser.country=US
      - name: Install Node modules
        run:  rm -rf node_modules && npm install
      - name: Run Jest test
        run: npm test
